### PR TITLE
OCPBUGS-34329: Update to Go v1.22, and OCP v4.17 and Kubernetes v1.30

### PR DESCRIPTION
**Pull request by pierreprinetti**
Update all dependencies except cluster-api-provider-openstack, which stays at v0.9.1. The bump of CAPO to v0.10 will be carried out in a separate PR.

Supersedes #116

### CODE REVIEW

**Comment by MaysaMacedo** [comment]
@pierreprinetti why are we bumping to go 1.22 instead of 1.21?

**Comment by pierreprinetti** [comment]
> why are we bumping to go 1.22 instead of 1.21? Is the bump of CAPO to v0.10 gonna happen on release 4.17?

I am still not sure whether we want to bump CAPO to v0.10 in MAPO at all.

I am proposing a bump to Go v1.22 for three reasons:
1. I see no reason to stick to an older Go version
2. Again on defaulting to the most recent version, I am comforted by the fact that there is an OCP image for 1.22
3. openshift/api uses 1.22 in 4.17, so we need 1.22 here to bump to the latest openshift/api.

Do you think we should stick to 1.21?

**Comment by MaysaMacedo** [comment]
@pierreprinetti I started thinking about this because[ the bot](https://github.com/openshift/machine-api-provider-openstack/pull/116/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R3) has previously bumped to 1.21, but your point about the api being 1.22 is a strong argument for us moving as well.
Also, I see the [openshift/kubernetes repo](https://github.com/openshift/kubernetes/blob/master/go.mod#L9) has been 1.21 for a while so likely soon there will be a bump to 1.22.

/lgtm

**Pull request merged**
