### PR TITLE
Bug 2067844: Update dependencies to K8s 1.24, go 1.18

### PR DESCRIPTION
**Pull request by damdo**
**What this PR does / why we need it**:
- Update the dependencies to K8s 1.24.
- Bump project to go 1.18.

### CODE REVIEW

**Comment by mandre** [comment]
https://github.com/openshift/release/pull/29091 is required to fix the `e2e-openstack-nfv-intel` job.
`e2e-openstack` failure seems unrelated to this patch.

**Review by mandre — COMMENTED** [review]
e2e-openstack failure is unrelated due to the CI infra. Let's merge the patch.
/lgtm
/approve

**Comment by damdo** [comment]
Cool! I'll add the bugzilla reference then.

**Pull request merged**
