### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by pierreprinetti**
Most notably, rebase onto Kubernetes v1.25 (which is the base to OpenShift v4.12).

A prerequisite of [OSASINFRA-2981](https://issues.redhat.com//browse/OSASINFRA-2981)

### CODE REVIEW

**Review by mandre — COMMENTED** [review]
It wasn't necessary to bother with multiple commits, you could have bumped all deps in a single commit.
/lgtm

**Comment by pierreprinetti** [comment]
The CI failure is unrelated:
* [job history](https://prow.ci.openshift.org/job-history/gs/origin-ci-test/logs/periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.12-e2e-openstack-nfv-intel)
* [bug report](https://issues.redhat.com/browse/OCPBUGS-1235)

@mandre can you override CI?

**Comment by mandre** [comment]
Let's try again, with the correct incantation this time.
/override ci/prow/e2e-openstack-nfv-intel

**Pull request merged**
