### PR TITLE
Bug 2037484: Dep bump

### PR DESCRIPTION
**Pull request by pierreprinetti**
This PR contains two commits:

* Update test tooling. Bumps ginkgo and gomega
* Remove a dependency on klog v1 replacing it with klog v2

Deferring any further dependency bump until after:
* the module name is fixed: #12
* go.mod's Go version is set to 1.17: #9

### CODE REVIEW

**Comment by pierreprinetti** [comment]
```
level=fatal msg=failed to initialize the cluster: Some cluster operators are still updating: authentication, console
```

/retest

**Review by mandre — COMMENTED** [review]
/retest

**Comment by pierreprinetti** [comment]
Depends on https://github.com/openshift/machine-api-provider-openstack/pull/14

**Comment by pierreprinetti** [comment]
This is ready for a review.

**Comment by iamemilio** [comment]
/lgtm
the e2e test is down right now

**Pull request merged**
