### PR TITLE
WIP: Update MAPO to use types from openshift/api

### PR DESCRIPTION
**Pull request by mdbooth**
Depends on https://github.com/openshift/api/pull/1129

### CODE REVIEW

**Comment by mdbooth** [comment]
Will have to retest e2e-openstack when the cert on rdo.vexxhost.ca:5000 has been updated.

**Comment by pierreprinetti** [comment]
/close
in favour of https://github.com/openshift/machine-api-provider-openstack/pull/46

What's not in that other PR is saved here as a TODO: https://issues.redhat.com/browse/OCPBUGS-2153

**Pull request closed without merging**
